### ISSUE TITLE
ChatImpl.parseMessage : boolean expression must not be null

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [ConnectyCube/connectycube-flutter-sdk-releases#20]
**Platform (use [x])**
[ ] Android
[ ] iOS

**Device info**
Manufacture: [e.g. Apple inc.]
Model: [e.g. iPhone 11 Pro Max]
OS version: [e.g. 13.5.2]

**Describe the bug:**
Unhandled Exception: Failed assertion: boolean expression must not be null
ChatImpl.parseMessage (package:xmpp_stone/src/chat/Chat.dart:51:49)

while i am typing or sending something from the one mobile to another this is what i got

please Help!

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**
```
log here
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Failed assertion: boolean expression must not be null
    #0      ChatImpl.parseMessage (package:xmpp_stone/src/chat/Chat.dart:51:49)
    #1      new ChatManager.<anonymous closure> (package:xmpp_stone/src/chat/ChatManager.dart:34:12)
    #2      _rootRunUnary (dart:async/zone.dart:1198:47)
    #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
    #8      _MapStream._handleData (dart:async/stream_pipe.dart:224:10)
    #9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
    #10     _rootRunUnary (dart:async/zone.dart:1198:47)
    #11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
    #16     _WhereStream._handleData (dart:async/stream_pipe.dart:199:12)
    #17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
    #18     _rootRunUnary (dart:async/zone.dart:1198:47)
    #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #22     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
    #23     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
    #24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
    #25     _rootRun (dart:async/zone.dart:1182:47)
    #26     _CustomZone.run (dart:async/zone.dart:1093:19)
    #27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
    #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
    #29     _rootRun (dart:async/zone.dart:1190:13)
    #30     _CustomZone.run (dart:async/zone.dart:1093:19)
    #31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
    #32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
    #33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Failed assertion: boolean expression must not be null
    #0      ChatImpl.parseMessage (package:xmpp_stone/src/chat/Chat.dart:51:49)
    #1      new ChatManager.<anonymous closure> (package:xmpp_stone/src/chat/ChatManager.dart:34:12)
    #2      _rootRunUnary (dart:async/zone.dart:1198:47)
    #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
    #8      _MapStream._handleData (dart:async/stream_pipe.dart:224:10)
    #9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
    #10     _rootRunUnary (dart:async/zone.dart:1198:47)
    #11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
    #16     _WhereStream._handleData (dart:async/stream_pipe.dart:199:12)
    #17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
    #18     _rootRunUnary (dart:async/zone.dart:1198:47)
    #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #22     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
    #23     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
    #24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
    #25     _rootRun (dart:async/zone.dart:1182:47)
    #26     _CustomZone.run (dart:async/zone.dart:1093:19)
    #27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
    #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
    #29     _rootRun (dart:async/zone.dart:1190:13)
    #30     _CustomZone.run (dart:async/zone.dart:1093:19)
    #31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
    #32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
    #33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
or
[Gist log](https://gist.github.com/)

**Actual result:**


**Expected behavior:**


**Additional info**
Add any other context about the problem here.

**Comment by TatankaConCube** [comment]
@BhavyKoshti9spl  please add more details about your issue, we need next:
- full log from both devices (sender and receiver), which contains sent and received stanzas;
- detailed steps to reproduce;
- can you reproduce the same issue on our [chat_sample](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/chat_sample);

**Comment by BhavyKoshti9spl** [comment]
> @BhavyKoshti9spl please add more details about your issue, we need next:
> 
> * full log from both devices (sender and receiver), which contains sent and received stanzas;
> * detailed steps to reproduce;
> * can you reproduce the same issue on our [chat_sample](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/chat_sample);

added please look!

**Comment by BhavyKoshti9spl** [comment]
@TatankaConCube 

1. now i am unable to reproduce it.
2. i am trying to type something or sending something.
3. nope works fine in chat sample

**Comment by TatankaConCube** [comment]
@BhavyKoshti9spl sorry, but without the required information, we can't help you.

**Comment by TatankaConCube** [comment]
I have investigated this issue on our chat sample and found out it issue happens in one of our dependency and does not affect the performance of our SDK
