### ISSUE TITLE
Call manager's stopCall function returns The method 'map' was called on null.

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [ConnectyCube/connectycube-flutter-sdk-releases#22]
The method 'map' was called on null.
Receiver: null
Tried calling: map<CubeMessage>(Closure: (int) => CubeMessage)

so now i am not able to leave the screen.

Steps : 
1. Sender device conference call to a single person.
2. Receiver device accept the call.
3. Now i am not able to end the call as _callManager.stopCall(); throws error and no further activities happens.

not sure this is reproducing in sample project or not btw i just copied the code from sample and its not working.

**Comment by TatankaConCube** [comment]
Just I built Android and iOS apps for tests and it works fine on both devices. Please, check the code on your side, looks like you did some mistakes during the copying code to your project.

**Comment by BhavyKoshti9spl** [comment]
I just got some logs : 

[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: [](0)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      BaseSession.switchCamera (package:connectycube_sdk/src/calls/models/call_base_session.dart:108:43)
#2      _ConversationCallScreenState._switchCamera (package:just_eat_the_warm/ui/call/call_screen.dart:576:18)
#3      _ConversationCallScreenState._getActionsPanel.<anonymous closure> (package:just_eat_the_warm/ui/call/call_screen.dart:518:36)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:990:20)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381:19)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:279:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
#22     _rootRunUnary (dart:async/zone.dart:1206:13)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#25     _invoke1 (dart:ui/hooks.dart:176:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)

**Comment by BhavyKoshti9spl** [comment]
I am attaching my both debug builds and steps to go to the call screen

you can check the issues on logs this issues are happening only some times and i am not getting the exact error.

[App 1](https://www.dropbox.com/s/16nj73zc0ie720j/app-debug_3430.apk?dl=0)
[App 2](https://www.dropbox.com/s/l4g5qk92z4koga0/app-debug_0644.apk?dl=0)

steps to go to the call screen : 
1. on top bar you will find the chat icon, click on that.
2. on chats tab click on the first dialog.
3. this is chat detail screen in this you will find the call icon on the top bar audio and video calls.
4. click from one device and in 2nd device please stay on the chat detail screen to receive a call 

while i am receiving the call and try to end the call its not working or sometimes i am getting errors on the mic buttons and speaker buttons also.

Please if you can see above debug applications and find the bug that would be good coz i am unable to find the exact scenario.

**Comment by BhavyKoshti9spl** [comment]
can you provide me some email where i can send debug apk so that you can check it better ?

**Comment by TatankaConCube** [comment]
you can use our public e-mail for support support@connectycube.com, just add a subject like 'Flutter SDK GitHub support' and add a link on this issue. But I'm not sure that your .apk will help to resolve your issue. You know your project better than me and you can compare your code and code of our sample and found differences.

**Comment by BhavyKoshti9spl** [comment]
> you can use our public e-mail for support [support@connectycube.com](mailto:support@connectycube.com), just add a subject like 'Flutter SDK GitHub support' and add a link on this issue. But I'm not sure that your .apk will help to resolve your issue. You know your project better than me and you can compare your code and code of our sample and found differences.

Thanks. looking forward to your positive reply.

**Comment by BhavyKoshti9spl** [comment]
Here are some logs of mobile who called the other one....

```
I/flutter (22808): 2020-12-11T18:36:53.114558: CB-SDK: : RCV(7): {
I/flutter (22808):    "janus": "event",
I/flutter (22808):    "session_id": 6740316000705608,
I/flutter (22808):    "sender": 8750560598752747,
I/flutter (22808):    "plugindata": {
I/flutter (22808):       "plugin": "janus.plugin.videoroom",
I/flutter (22808):       "data": {
I/flutter (22808):          "videoroom": "event",
I/flutter (22808):          "room": "2854230",
I/flutter (22808):          "leaving": 2866889
I/flutter (22808):       }
I/flutter (22808):    }
I/flutter (22808): }
I/flutter (22808): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.event, sessionId=6740316000705608}
I/flutter (22808): 2020-12-11T18:36:53.116924: CB-SDK: JanusSignaler: LeavePublisherEvent left userId= 2866889
I/flutter (22808): 2020-12-11T18:36:53.119838: CB-SDK: ConferenceSession: onLeaveParticipantEvent participantId= 2866889
I/flutter (22808): 2020-12-11T18:36:53.127497: CB-SDK: : SND(7): {"janus":"detach","session_id":6740316000705608,"transaction":"0a2d1cd8-a24a-4b6c-b361-3e737f151158","token":null,"handle_id":822269089486079}
I/flutter (22808): CB-SDK: _ConversationCallScreenState: onPublisherLeft 2866889
I/flutter (22808): 2020-12-11T18:36:53.130384: CB-SDK: ConferenceSession: onLeaveParticipantEvent publisherId= 2866889 cleaning all stuff
D/FlutterWebRTCPlugin(22808): onConnectionChangeCLOSED
I/org.webrtc.Logging(22808): AndroidVideoDecoder: release
I/BufferQueueConsumer(22808): [SurfaceTexture-7-22808-16](this:0x7161fdf000,id:16,api:3,p:22808,c:22808) setDefaultBufferSize: width=960 height=540
I/org.webrtc.Logging(22808): AndroidVideoDecoder: Releasing MediaCodec on output thread
I/BufferQueueConsumer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) setDefaultBufferSize: width=720 height=1280
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) queueBuffer: slot 1 is dropped, handle=0x7173b45a80
I/GED     (22808): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
D/BufferQueueProducer(22808): [SurfaceTexture-7-22808-16](this:0x7161fdf000,id:16,api:3,p:22808,c:22808) cancelBuffer: slot 0
D/BufferQueueProducer(22808): [SurfaceTexture-7-22808-16](this:0x7161fdf000,id:16,api:3,p:22808,c:22808) cancelBuffer: slot 2
D/BufferQueueProducer(22808): [SurfaceTexture-7-22808-16](this:0x7161fdf000,id:16,api:3,p:22808,c:22808) cancelBuffer: slot 3
D/BufferQueueProducer(22808): [SurfaceTexture-7-22808-16](this:0x7161fdf000,id:16,api:3,p:22808,c:22808) cancelBuffer: slot 5
D/BufferQueueProducer(22808): [SurfaceTexture-7-22808-16](this:0x7161fdf000,id:16,api:3,p:22808,c:22808) cancelBuffer: slot 6
D/BufferQueueProducer(22808): [SurfaceTexture-7-22808-16](this:0x7161fdf000,id:16,api:3,p:22808,c:22808) cancelBuffer: slot 7
D/BufferQueueProducer(22808): [SurfaceTexture-7-22808-16](this:0x7161fdf000,id:16,api:3,p:22808,c:22808) cancelBuffer: slot 8
D/BufferQueueProducer(22808): [SurfaceTexture-7-22808-16](this:0x7161fdf000,id:16,api:3,p:22808,c:22808) cancelBuffer: slot 9
D/SurfaceUtils(22808): disconnecting from surface 0x715de0c010, reason disconnectFromSurface
D/Surface (22808): Surface::disconnect(this=0x715de0c000,api=3)
I/BufferQueueProducer(22808): [SurfaceTexture-7-22808-16](this:0x7161fdf000,id:16,api:3,p:22808,c:22808) disconnect(P): api 3
I/org.webrtc.Logging(22808): AndroidVideoDecoder: Release on output thread done
I/org.webrtc.Logging(22808): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging(22808): SurfaceTextureHelper: dispose()
D/RefBase (22808): RefBase: Explicit destruction, weak count = 0 (in 0x71a3291128)
W/RefBase (22808): CallStack::getCurrentInternal not linked, returning null
W/RefBase (22808): CallStack::logStackInternal not linked
I/GPUAUX  (22808): [AUX]~GPUAUXContext:77: destory: 0x7138d13fc0
I/GED     (22808): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) queueBuffer: slot 0 is dropped, handle=0x7173b47880
I/flutter (22808): CB-SDK: PeerConnection: onIceConnectionState changed to RTCIceConnectionState.RTCIceConnectionStateClosed for opponent 2866889
I/flutter (22808): CB-SDK: : onConnectionClosedForUser userId= 2866889
I/flutter (22808): CB-SDK: _ConversationCallScreenState: _removeMediaStream for user 2866889
W/FlutterWebRTCPlugin(22808): FlutterRTCVideoRenderer.setVideoTrack, set video track to null
I/GED     (22808): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/flutter (22808): 2020-12-11T18:36:53.237955: CB-SDK: ConferenceSession: signaler leave
[log] ---Xmpp Sending:---
I/flutter (22808): 2020-12-11T18:36:53.239085: CB-SDK: : SND(7): {"janus":"message","session_id":6740316000705608,"transaction":"7bce9590-c069-40b9-a47c-4a366c95ea01","token":null,"handle_id":8750560598752747,"body":{"id":2854230,"feed":null,"ptype":null,"room":"2854230","request":"leave"}}
I/flutter (22808): 2020-12-11T18:36:53.240764: CB-SDK: ConferenceSession: disposeSession opponentId 2854230
I/flutter (22808): 2020-12-11T18:36:53.241932: CB-SDK: ConferenceSession: closeConnectionForOpponent opponentId 2854230 success
I/flutter (22808): CB-SDK: BaseSession: closeConnectionForOpponent, _channels.length = 1
[log] <message id="5fd36eedcc8874bd5d7cb8f2" type="headline" to="2866889-3830@chat.connectycube.com">
  <body/>
  <extraParams xmlns="jabber:client">
    <date_sent>1607692013235</date_sent>
    <save_to_history>1</save_to_history>
    <janusRoomId>2854230</janusRoomId>
    <callEnd>1</callEnd>
    <moduleIdentifier>SystemNotifications</moduleIdentifier>
  </extraParams>
</message>
I/flutter (22808): CB-SDK: BaseSession: closeConnectionForOpponent, left channels = 2866889
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) queueBuffer: slot 1 is dropped, handle=0x7173b44040
I/flutter (22808): 2020-12-11T18:36:53.242627: CB-SDK: ConferenceSession: disposeSession opponentId 2866889
I/flutter (22808): 2020-12-11T18:36:53.242880: CB-SDK: ConferenceSession: closeConnectionForOpponent opponentId 2866889 success
I/flutter (22808): CB-SDK: BaseSession: closeConnectionForOpponent, _channels.length = 0
I/flutter (22808): CB-SDK: BaseSession: closeCurrentSession
I/flutter (22808): CB-SDK: BaseSession: _notifySessionClosed
I/flutter (22808): CB-SDK: _ConversationCallScreenState: _onSessionClosed
I/BufferQueueProducer(22808): [SurfaceTexture-5-22808-13](this:0x7161d1a800,id:13,api:4,p:740,c:22808) queueBuffer: fps=29.59 dur=1013.72 max=42.25 min=27.85
D/FlutterWebRTCPlugin(22808): onConnectionChangeCLOSED
I/flutter (22808): 2020-12-11T18:36:53.245572: CB-SDK: ConferenceSession: Trying to leave from room, while session has been already closed
I/org.webrtc.Logging(22808): WebRtcAudioRecordExternal: stopRecording
I/org.webrtc.Logging(22808): WebRtcAudioRecordExternal: stopThread
I/flutter (22808): CB-SDK: PeerConnection: onSignalingState changed to RTCSignalingState.RTCSignalingStateClosed for opponent 2866889
I/org.webrtc.Logging(22808): EglRenderer: Duration: 4001 ms. Frames received: 118. Dropped: 0. Rendered: 118. Render fps: 29.5. Average render time: 3939 us. Average swapBuffer time: 2357 us.
I/GED     (22808): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) queueBuffer: slot 0 is dropped, handle=0x7173b47600
D/AudioRecord(22808): stop mSessionID=95841
D/AudioRecord(22808): PackageName[com.just_eat_the_warm], uid[10777]
D/AudioRecord(22808): stop(8402): 0x717d601500, mActive:1
I/BufferQueue(22808): [SurfaceTexture-7-22808-16](this:0x7161fdf000,id:16,api:3,p:-1,c:-1) ~BufferQueueCore
D/RefBase (22808): RefBase: Explicit destruction, weak count = 0 (in 0x7161fe0458)
W/RefBase (22808): CallStack::getCurrentInternal not linked, returning null
W/RefBase (22808): CallStack::logStackInternal not linked
I/GED     (22808): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) queueBuffer: slot 1 is dropped, handle=0x7173b44040
I/flutter (22808): markAsReadIfNeed message= {_id: 5fd1cbc2068fe6fd7446f85e, chat_dialog_id: 5fc73389ca8bf416b78d922d, message: 😁, date_sent: 1607584706, sender_id: 2866889, recipient_id: 2854230, read_ids: [2866889, 2854230], delivered_ids: [2866889, 2854230], views_count: 0, attachments: [], id: null, created_at: 2020-12-10 07:18:28.000Z, updated_at: 2020-12-10 07:20:21.000Z}, isOpponentMsgRead= true
I/flutter (22808): markAsReadIfNeed message= {_id: 5fd0660a86df35fa71680179, chat_dialog_id: 5fc73389ca8bf416b78d922d, message: heeejsjjshsgghjd, date_sent: 1607493130, sender_id: 2866889, recipient_id: 2854230, read_ids: [2866889, 2854230], delivered_ids: [2866889, 2854230], views_count: 0, attachments: [], id: null, created_at: 2020-12-09 05:52:08.000Z, updated_at: 2020-12-09 05:52:09.000Z}, isOpponentMsgRead= true
I/GED     (22808): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) queueBuffer: slot 0 is dropped, handle=0x7173b47600
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) queueBuffer: fps=29.67 dur=1011.03 max=65.02 min=19.85
D/AudioRecord(22808): stop(8402) done
D/AudioService(22808): broadcastRecorderState:com.just_eat_the_warm
I/org.webrtc.Logging(22808): WebRtcAudioRecordExternal: doAudioRecordStateCallback: STOP
I/org.webrtc.Logging(22808): WebRtcAudioEffectsExternal: release
I/org.webrtc.Logging(22808): WebRtcAudioRecordExternal: releaseAudioResources
D/AudioRecord(22808): stop mSessionID=95841
D/AudioRecord(22808): PackageName[com.just_eat_the_warm], uid[10777]
D/AudioRecord(22808): stop(8402): 0x717d601500, mActive:0
D/AudioService(22808): broadcastRecorderState:com.just_eat_the_warm
D/AudioRecord(22808): stop mSessionID=95841
D/AudioRecord(22808): PackageName[com.just_eat_the_warm], uid[10777]
D/AudioRecord(22808): stop(8402): 0x717d601500, mActive:0
D/AudioRecord(22808): ~AudioRecord(8402): mStatus 0
D/AudioRecord(22808): stop mSessionID=95841
D/AudioRecord(22808): PackageName[com.just_eat_the_warm], uid[10777]
D/AudioRecord(22808): stop(8402): 0x717d601500, mActive:0
D/AudioRecord(22808): PackageName[com.just_eat_the_warm], uid[10777]
I/flutter (22808): 2020-12-11T18:36:53.353543: CB-SDK: : RCV(7): {
I/flutter (22808):    "janus": "success",
I/flutter (22808):    "session_id": 6740316000705608,
I/flutter (22808):    "transaction": "0a2d1cd8-a24a-4b6c-b361-3e737f151158"
I/flutter (22808): }
I/flutter (22808): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.success, sessionId=6740316000705608}
I/flutter (22808): 2020-12-11T18:36:53.355066: CB-SDK: : RCV(7): {
I/flutter (22808):    "janus": "detached",
I/flutter (22808):    "session_id": 6740316000705608,
I/flutter (22808):    "sender": 822269089486079
I/flutter (22808): }
I/flutter (22808): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.detached, sessionId=6740316000705608}
I/GED     (22808): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/org.webrtc.Logging(22808): CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging(22808): VolumeLogger: stop@[name=worker_thread - 23834, id=17951]
I/org.webrtc.Logging(22808): WebRtcAudioTrackExternal: stopPlayout
I/org.webrtc.Logging(22808): WebRtcAudioTrackExternal: underrun count: 0
I/org.webrtc.Logging(22808): WebRtcAudioTrackExternal: stopThread
I/org.webrtc.Logging(22808): WebRtcAudioTrackExternal: Stopping the AudioTrackThread...
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) queueBuffer: slot 0 is dropped, handle=0x7173b47600
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) queueBuffer: slot 2 is dropped, handle=0x7173b45800
I/org.webrtc.Logging(22808): WebRtcAudioTrackExternal: AudioTrackThread has now been stopped.
I/org.webrtc.Logging(22808): WebRtcAudioTrackExternal: Calling AudioTrack.stop...
D/AudioTrack(22808): stop(sessionID=95833)
D/AudioTrack(22808): stop(8400): 0x71ff138000, prior state:STATE_ACTIVE
D/AudioTrack(22808): stop(8400): called with 9218400 frames delivered
D/AudioTrack(22808): stop(8400): 0x71ff138000 stop done
I/org.webrtc.Logging(22808): WebRtcAudioTrackExternal: AudioTrack.stop is done.
I/org.webrtc.Logging(22808): WebRtcAudioTrackExternal: doAudioTrackStateCallback: 1
I/org.webrtc.Logging(22808): WebRtcAudioTrackExternal: releaseAudioResources
D/AudioTrack(22808): stop(sessionID=95833)
D/AudioTrack(22808): stop(8400): 0x71ff138000, prior state:STATE_STOPPED
D/AudioTrack(22808): ~AudioTrack(8400): 0x71ff138000
D/AudioTrack(22808): ~AudioTrack(sessionID=95833)
D/AudioTrack(22808): stop(sessionID=95833)
D/AudioTrack(22808): stop(8400): 0x71ff138000, prior state:STATE_STOPPED
I/org.webrtc.Logging(22808): NetworkMonitor: Stop monitoring with native observer 486975196096
I/org.webrtc.Logging(22808): NetworkMonitorAutoDetect: Unregister network callback
I/org.webrtc.Logging(22808): NetworkMonitorAutoDetect: Unregister network callback
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) queueBuffer: slot 0 is dropped, handle=0x7173b47600
I/flutter (22808): CB-SDK: PeerConnection: onIceConnectionState changed to RTCIceConnectionState.RTCIceConnectionStateClosed for opponent 2854230
I/org.webrtc.Logging(22808): CameraCapturer: Stop capture
I/org.webrtc.Logging(22808): CameraCapturer: Stop capture: Nulling session
I/org.webrtc.Logging(22808): CameraCapturer: Stop capture done
I/org.webrtc.Logging(22808): CameraCapturer: dispose
I/org.webrtc.Logging(22808): Camera2Session: Stop camera2 session on camera 1
I/org.webrtc.Logging(22808): CameraCapturer: Stop capture
I/org.webrtc.Logging(22808): CameraCapturer: Stop capture: No session open
I/org.webrtc.Logging(22808): Camera2Session: Stop internal
I/org.webrtc.Logging(22808): CameraCapturer: Stop capture done
I/org.webrtc.Logging(22808): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging(22808): EglRenderer: Releasing.
I/org.webrtc.Logging(22808): GlShader: Deleting shader.
I/org.webrtc.Logging(22808): EglRenderer: eglBase detach and release.
D/Surface (22808): Surface::disconnect(this=0x715dd06000,api=1)
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-15](this:0x71a29d7800,id:15,api:1,p:22808,c:22808) disconnect(P): api 1
I/org.webrtc.Logging(22808): EglRenderer: Releasing done.
I/org.webrtc.Logging(22808): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(22808): EglRenderer: Releasing.
I/org.webrtc.Logging(22808): GlShader: Deleting shader.
I/org.webrtc.Logging(22808): EglRenderer: eglBase detach and release.
D/Surface (22808): Surface::disconnect(this=0x717480f000,api=1)
I/BufferQueueProducer(22808): [SurfaceTexture-0-22808-14](this:0x7291190800,id:14,api:1,p:22808,c:22808) disconnect(P): api 1
I/org.webrtc.Logging(22808): EglRenderer: Releasing done.
I/org.webrtc.Logging(22808): EglRenderer: Quitting render thread.
I/flutter (22808): CB-SDK: PeerConnection: onSignalingState changed to RTCSignalingState.RTCSignalingStateClosed for opponent 2854230
D/BufferQueueProducer(22808): [SurfaceTexture-5-22808-13](this:0x7161d1a800,id:13,api:4,p:740,c:22808) cancelBuffer: slot 7
D/BufferQueueProducer(22808): [SurfaceTexture-5-22808-13](this:0x7161d1a800,id:13,api:4,p:740,c:22808) cancelBuffer: slot 3
D/BufferQueueProducer(22808): [SurfaceTexture-5-22808-13](this:0x7161d1a800,id:13,api:4,p:740,c:22808) cancelBuffer: slot 4
D/BufferQueueProducer(22808): [SurfaceTexture-5-22808-13](this:0x7161d1a800,id:13,api:4,p:740,c:22808) cancelBuffer: slot 5
I/BufferQueueProducer(22808): [SurfaceTexture-5-22808-13](this:0x7161d1a800,id:13,api:4,p:740,c:22808) queueBuffer: slot 2 is dropped, handle=0x715aaf1a40
I/flutter (22808): 2020-12-11T18:36:53.570520: CB-SDK: : RCV(7): {
I/flutter (22808):    "janus": "ack",
I/flutter (22808):    "session_id": 6740316000705608,
I/flutter (22808):    "transaction": "7bce9590-c069-40b9-a47c-4a366c95ea01"
I/flutter (22808): }
I/flutter (22808): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.ack, sessionId=6740316000705608}
I/flutter (22808): 2020-12-11T18:36:53.571358: CB-SDK: ConferenceSession: signaler detachHandleIdAll
I/flutter (22808): 2020-12-11T18:36:53.571868: CB-SDK: : SND(7): {"janus":"detach","session_id":6740316000705608,"transaction":"cece9251-843a-4eac-8da6-324ddb465485","token":null,"handle_id":8750560598752747}
I/flutter (22808): 2020-12-11T18:36:53.572447: CB-SDK: ConferenceSession: signaler destroySession
I/flutter (22808): 2020-12-11T18:36:53.573031: CB-SDK: : SND(7): {"janus":"destroy","session_id":6740316000705608,"transaction":"ca49766b-5e34-416e-a40d-f729004314f6","token":null}
I/flutter (22808): 2020-12-11T18:36:53.574527: CB-SDK: : RCV(7): {
I/flutter (22808):    "janus": "event",
I/flutter (22808):    "session_id": 6740316000705608,
I/flutter (22808):    "transaction": "7bce9590-c069-40b9-a47c-4a366c95ea01",
I/flutter (22808):    "sender": 8750560598752747,
I/flutter (22808):    "plugindata": {
I/flutter (22808):       "plugin": "janus.plugin.videoroom",
I/flutter (22808):       "data": {
I/flutter (22808):          "videoroom": "event",
I/flutter (22808):          "room": "2854230",
I/flutter (22808):          "leaving": "ok"
I/flutter (22808):       }
I/flutter (22808):    }
I/flutter (22808): }
I/flutter (22808): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.event, sessionId=6740316000705608}
I/flutter (22808): 2020-12-11T18:36:53.575192: CB-SDK: JanusSignaler: isLeaveCurrentUserEvent leavingOk? true
I/flutter (22808): 2020-12-11T18:36:53.575313: CB-SDK: ConferenceSession: onLeaveCurrentUserEvent success= true
I/BufferQueueProducer(22808): [SurfaceTexture-5-22808-13](this:0x7161d1a800,id:13,api:4,p:740,c:22808) disconnect(P): api 4
E/libc    (22808): Access denied finding property "camera.aux.packagelist"
W/Binder:22808_1(22808): type=1400 audit(0.0:79834): avc: denied { read } for name="u:object_r:mtkcam_prop:s0" dev="tmpfs" ino=11554 scontext=u:r:untrusted_app:s0:c9,c259,c512,c768 tcontext=u:object_r:mtkcam_prop:s0 tclass=file permissive=0
I/org.webrtc.Logging(22808): Camera2Session: Stop done
W/st_eat_the_war(22808): Long monitor contention with owner main (26609) at boolean android.os.BinderProxy.transactNative(int, android.os.Parcel, android.os.Parcel, int)(BinderProxy.java:-2) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 145ms
I/org.webrtc.Logging(22808): Camera2Session: Camera device closed.
D/FlutterWebRTCPlugin(22808): CameraEventsHandler.onFirstFrameAvailable
I/flutter (22808): 2020-12-11T18:36:53.693350: CB-SDK: : RCV(7): {
I/flutter (22808):    "janus": "hangup",
I/flutter (22808):    "session_id": 6740316000705608,
I/flutter (22808):    "sender": 8750560598752747,
I/flutter (22808):    "reason": "DTLS alert"
I/flutter (22808): }
I/flutter (22808): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.hangup, sessionId=6740316000705608}
I/flutter (22808): 2020-12-11T18:36:53.693833: CB-SDK: JanusSignaler: WsHangUp packet reason= DTLS alert
I/flutter (22808): CB-SDK: _ConversationCallScreenState: onError Instance of 'WsHangUpException'

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
A RTCVideoRendererNative was used after being disposed.
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (22808): 2020-12-11T18:36:53.781206: CB-SDK: : RCV(7): {
I/flutter (22808):    "janus": "success",
I/flutter (22808):    "session_id": 6740316000705608,
I/flutter (22808):    "transaction": "cece9251-843a-4eac-8da6-324ddb465485"
I/flutter (22808): }
I/flutter (22808): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.success, sessionId=6740316000705608}
I/flutter (22808): 2020-12-11T18:36:53.786222: CB-SDK: : RCV(7): {
I/flutter (22808):    "janus": "success",
I/flutter (22808):    "session_id": 6740316000705608,
I/flutter (22808):    "transaction": "ca49766b-5e34-416e-a40d-f729004314f6"
I/flutter (22808): }
I/flutter (22808): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.success, sessionId=6740316000705608}
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='37'/>
[log] D/[StreamManagementModule]: Delivered: 5fd36eedcc8874bd5d7cb8f2
D/ViewRootImpl(22808): [TouchInput][ViewRootImpl] MotionEvent { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=134012843, downTime=134012843 } moveCount:0
D/ViewRootImpl(22808): [TouchInput][ViewRootImpl] MotionEvent { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=134012910, downTime=134012843 } moveCount:0

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The method 'map' was called on null.
Receiver: null
Tried calling: map<CubeMessage>(Closure: (int) => CubeMessage)
════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl(22808): [TouchInput][ViewRootImpl] MotionEvent { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=134013594, downTime=134013594 } moveCount:0
D/ViewRootImpl(22808): [TouchInput][ViewRootImpl] MotionEvent { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=134013668, downTime=134013594 } moveCount:0

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The method 'map' was called on null.
Receiver: null
Tried calling: map<CubeMessage>(Closure: (int) => CubeMessage)
════════════════════════════════════════════════════════════════════════════════════════════════════
```
