### ISSUE TITLE
Unhandled Exception: PlatformException(videoRendererDispose, videoRendererDispose(): render [4] not found !, null, null)

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [ConnectyCube/connectycube-flutter-sdk-releases#28]
**Platform (use [x])**
[x] Android
[] iOS

**Device info**
Manufacture: [e.g. Nokia, Xaiomi.]
Model: [e.g. Nokia 6.1, Redmi note 8 pro]
OS version: [e.g. Android P]

**Describe the bug:**
while i start any call after sometimes call is being disconnected after some times. it happens sometimes so i dont have proper issue.

**Steps to Reproduce:**
1.  start a call
2. receive a call in other call
3. wait for a minute.
4. call is disconnected by it self.

**Logs:**
This logs are from receiver side.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(videoRendererDispose, videoRendererDispose(): render [4] not found !, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      RTCVideoRendererNative.dispose (package:flutter_webrtc/src/native/rtc_video_renderer_impl.dart:51:20)
<asynchronous suspension>
#4      RTCVideoRenderer.dispose (package:flutter_webrtc/src/rtc_video_renderer.dart:26:22)
#5      _ConversationCallScreenState.dispose.<anonymous closure> (package:just_eat_the_warm/ui/call/call_screen.dart:277:20)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#7      _ConversationCallScreenState.dispose (package:just_eat_the_warm/ui/call/call_screen.dart:275:13)
#8      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4854:12)
#9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1998:13)
#10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#11     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#29     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#39

[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
I/flutter ( 4626): 2021-01-01T07:59:02.995579: CB-SDK: : RCV(2): {
I/flutter ( 4626):    "janus": "event",
I/flutter ( 4626):    "session_id": 3766531734663075,
I/flutter ( 4626):    "transaction": "4aa01689-f9f3-43aa-940f-69bb0bad040b",
I/flutter ( 4626):    "sender": 5171076368033602,
I/flutter ( 4626):    "plugindata": {
I/flutter ( 4626):       "plugin": "janus.plugin.videoroom",
I/flutter ( 4626):       "data": {
I/flutter ( 4626):          "videoroom": "event",
I/flutter ( 4626):          "room": "2854230",
I/flutter ( 4626):          "leaving": "ok"
I/flutter ( 4626):       }
I/flutter ( 4626):    }
I/flutter ( 4626): }
I/flutter ( 4626): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.event, sessionId=3766531734663075}
I/flutter ( 4626): 2021-01-01T07:59:02.996529: CB-SDK: JanusSignaler: isLeaveCurrentUserEvent leavingOk? true
I/flutter ( 4626): 2021-01-01T07:59:02.996715: CB-SDK: ConferenceSession: onLeaveCurrentUserEvent success= true
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='15'/>
I/flutter ( 4626): 2021-01-01T07:59:03.000854: CB-SDK: : RCV(2): {
I/flutter ( 4626):    "janus": "hangup",
I/flutter ( 4626):    "session_id": 3766531734663075,
[log] D/[StreamManagementModule]: Delivered: 5feeab905b336afeb450da21
I/flutter ( 4626):    "sender": 5171076368033602,
I/flutter ( 4626):    "reason": "DTLS alert"
I/flutter ( 4626): }
I/flutter ( 4626): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.hangup, sessionId=3766531734663075}
I/flutter ( 4626): 2021-01-01T07:59:03.001629: CB-SDK: JanusSignaler: WsHangUp packet reason= DTLS alert
I/flutter ( 4626): CB-SDK: _ConversationCallScreenState: onError Instance of 'WsHangUpException'
[log] D/[StreamManagementModule]: Delivered: 5feeab905b336afeb450da22
[log] ---Xmpp Receiving:---
I/flutter ( 4626): CB-SDK: : parseCallMessage cubeMessage= {_id: 5feeab905b336afeb450da22, chat_dialog_id: null, message: null, date_sent: 1609477008023, sender_id: 2866889, recipient_id: 2866889, read_ids: null, delivered_ids: null, views_count: null, attachments: [], id: null, created_at: null, updated_at: null, save_to_history: 1, janusRoomId: 2854230, callEnd: 1, moduleIdentifier: SystemNotifications}
I/flutter ( 4626): 2021-01-01T07:59:03.006406: CB-SDK: : RCV(2): {
I/flutter ( 4626):    "janus": "success",
I/flutter ( 4626):    "session_id": 3766531734663075,
I/flutter ( 4626):    "transaction": "2d63bc69-21ef-4328-b740-3ff3212f05fe"
I/flutter ( 4626): }
I/flutter ( 4626): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.success, sessionId=3766531734663075}
[log] <message id="5feeab905b336afeb450da22" type="headline" to="2866889-3830@chat.connectycube.com" xmlns="jabber:client" from="2866889-3830@chat.connectycube.com/flutter_1bd822d0b42bf08a">
<body/><extraParams xmlns="jabber:client">
  <date_sent>1609477008023</date_sent><save_to_history>1</save_to_history><janusRoomId>2854230</janusRoomId><callEnd>1</callEnd><moduleIdentifier>SystemNotifications</moduleIdentifier></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
I/flutter ( 4626): 2021-01-01T07:59:03.012705: CB-SDK: : RCV(2): {
I/flutter ( 4626):    "janus": "success",
I/flutter ( 4626):    "session_id": 3766531734663075,
I/flutter ( 4626):    "transaction": "ae1e5968-3b53-48c3-8f1e-04866035d052"
I/flutter ( 4626): }
[log] ---Xmpp Sending:---
I/flutter ( 4626): CB-SDK: : _onPacketReceived= WsPacket{messageType=Type.success, sessionId=3766531734663075}

```

or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**
call should only be disconnected when someone end it.

**Additional info**

**Comment by BhavyKoshti9spl** [comment]
Haven't checked on the sample but I am facing this, also when I implemented the [add user to call](https://developers.connectycube.com/flutter/videocalling-conference?id=adding-user-to-call) the first person receives the same response and it removes from the call. 

this bug i posted for the condition when only 2 persons are in the call. then it disconnected after 1 min approx.

when i implemented adding user functionality in a live call same happened but this time first person gets removed from the call.
scenario : first person calls 2nd person then after some time he adds 3rd person then 3rd person accepts the call after that in 5-6 secs first person removes from the conference call. but 2nd person and 3rd person remain in that call.

Please try to add this functionality to the existing [sample](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/conf_call_sample) so that someone can implement it easily.
