### ISSUE TITLE
Crash after receiving a message reaction.

### ISSUE THREAD

**Issue by pedrostick3** [ConnectyCube/connectycube-flutter-sdk-releases#86]
**Platform (use [x])**
[x] Android
[] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: Google
Model: Pixel 4
OS version: Android

**Describe the bug:**
Sending a reaction of a message, makes a crash after receiving it.
I'm using your 
 `CubeChatConnection.instance.chatMessagesManager.chatMessagesStream.listen` method to receive the incoming messages.
 It reports a null safety problem on `getUserIdFromGroupChatJid` method, in `connectycube_sdk-2.3.0\lib\src\chat\realtime\utils\jid_utils.dart` file.
I explained my solution on the Aditional Info section of this issue.

**Steps to Reproduce:**
1. Send Message Reaction; 
2. Automatically receive the message by `CubeChatConnection.instance.chatMessagesManager.chatMessagesStream.listen` method;
3. Error appears refering a bad null safety opperation in this library on `connectycube_sdk-2.3.0\lib\src\chat\realtime\utils\jid_utils.dart` in method `getUserIdFromGroupChatJid`;

**Logs:**
```
[log] D/[StanzaParser]: No id found for stanza
E/flutter (21563): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (21563): #0      getUserIdFromGroupChatJid
E/flutter (21563): #1      new CubeMessage.fromStanza
E/flutter (21563): #2      ChatMessagesManager.acceptMessage
E/flutter (21563): #3      new GlobalMessagesManager._private.<anonymous closure>
E/flutter (21563): #4      _WhereStream._handleData (dart:async/stream_pipe.dart:189:24)
E/flutter (21563): #5      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (21563): #6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (21563): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (21563): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (21563): #9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (21563): #10     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (21563): #11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (21563): #12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (21563): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (21563): #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (21563): #15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (21563): #16     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter (21563): #17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (21563): #18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (21563): #19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (21563): #20     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (21563): #21     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (21563): #22     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (21563): #23     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (21563): #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (21563):
```

**Actual result:**
Bad income message makes a crash, after reacting to it.

**Expected behavior:**
Good income message, after reacting to it.

**Additional info**
I fixed it by going to this file `connectycube_sdk-2.3.0\lib\src\chat\realtime\utils\jid_utils.dart` and changed the method  `getUserIdFromGroupChatJid` from this:
```
int getUserIdFromGroupChatJid(Jid jid) {
  return int.parse(jid.resource!);
}
```

to this:

```
int getUserIdFromGroupChatJid(Jid jid) {
  return int.parse(jid.resource ?? '0'); // this should be a default value if it's null
}
```

Hope it helped :)
Please fix this bug and contact me when you merge this into a new package version so i can update it ;)

**Comment by TatankaConCube** [comment]
@pedrostick3 I'm currently working on this feature for the Flutter platform and will publish a new version soon.

**Comment by pedrostick3** [comment]
Thank you very much! :)
Can you give me an estimate of when it will be published?

**Comment by TatankaConCube** [comment]
I plan to do it in a few days

**Comment by TatankaConCube** [comment]
@pedrostick3 the new version was published today, please use version [2.4.0](https://pub.dev/packages/connectycube_sdk/versions/2.4.0)

**Comment by TatankaConCube** [comment]
Could you please provide full log not error only? It should be with xmpp stanzas which provides the error. And say which platform do you use for adding the reaction.

**Comment by pedrostick3** [comment]
The platform i use to add the reaction is Android (Flutter) using your Server API requests. I've just checked your documentation again (to understand if something was changed) [https://developers.connectycube.com/server/chat?id=addremove-reactions] but it shows the same as before.

This is the full log:
```
Restarted application in 2 060ms.
[log] D/[Connection]: State: XmppConnectionState.SocketOpening
[log] D/[Connection]: State: XmppConnectionState.SocketOpened
[log] D/[Connection]: processInitialStream
[log] D/[ConnectionNegotiatorManager]: Negotiating features
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator true
[log] D/[ConnectionNegotiatorManager]: ACTIVE FEATURE: {name: SaslAuthenticationFeature, name_space: null, priority: 1000, state: NegotiatorState.NEGOTIATING}, isReady: true
[log] D/[Connection]: State: XmppConnectionState.Authenticated
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator true
[log] D/[ConnectionNegotiatorManager]: ACTIVE FEATURE: {name: StreamManagementModule, name_space: null, priority: 1000, state: NegotiatorState.NEGOTIATING}, isReady: true
[log] D/[ConnectionNegotiatorManager]: Feature Started Parsing
[log] D/[Connection]: processInitialStream
[log] D/[ConnectionNegotiatorManager]: Negotiating features
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator true
[log] D/[ConnectionNegotiatorManager]: ACTIVE FEATURE: {name: BindingResourceConnectionNegotiator, name_space: null, priority: 100, state: NegotiatorState.NEGOTIATING}, isReady: true
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator false
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator true
[log] D/[ConnectionNegotiatorManager]: ACTIVE FEATURE: {name: SessionInitiationNegotiator, name_space: null, priority: 1000, state: NegotiatorState.NEGOTIATING}, isReady: true
[log] D/[Connection]: State: XmppConnectionState.SessionInitialized
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator false
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator true
[log] D/[ConnectionNegotiatorManager]: ACTIVE FEATURE: {name: ServiceDiscoveryNegotiator, name_space: null, priority: 1000, state: NegotiatorState.NEGOTIATING}, isReady: true
[log] E/[ConnectionNegotiatorManager]: ADDING FEATURES count: 16 [Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature', Instance of 'Feature']
[log] D/[ConnectionNegotiatorManager]: Adding negotiator: {name: urn:xmpp:carbons, name_space: null, priority: 1000, state: NegotiatorState.IDLE}, isReady: true [Instance of 'Feature']
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator false
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator true
[log] D/[ConnectionNegotiatorManager]: ACTIVE FEATURE: {name: urn:xmpp:carbons, name_space: null, priority: 1000, state: NegotiatorState.NEGOTIATING}, isReady: true
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator false
[log] D/[ConnectionNegotiatorManager]: No matching negotiator
[log] D/[Connection]: State: XmppConnectionState.Ready
[log] D/[StanzaParser]: No id found for stanza
[log] D/[StreamManagementModule]: Delivered: EKQDNGKKB
[log] D/[StreamManagementModule]: Delivered: SJJQADJPM
[log] D/[StreamManagementModule]: Delivered: VVKDSOOEX
[log] D/[StreamManagementModule]: Delivered: UKXAPJJOH
[log] D/[StreamManagementModule]: Delivered stanza without id presence
[log] D/[StanzaParser]: No id found for stanza
E/flutter (11092): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (11092): #0      getUserIdFromGroupChatJid
E/flutter (11092): #1      new CubeMessage.fromStanza
E/flutter (11092): #2      ChatMessagesManager.acceptMessage
E/flutter (11092): #3      new GlobalMessagesManager._private.<anonymous closure>
E/flutter (11092): #4      _WhereStream._handleData (dart:async/stream_pipe.dart:189:24)
E/flutter (11092): #5      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (11092): #6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (11092): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (11092): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (11092): #9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (11092): #10     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (11092): #11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (11092): #12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (11092): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (11092): #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (11092): #15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (11092): #16     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter (11092): #17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (11092): #18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (11092): #19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (11092): #20     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (11092): #21     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (11092): #22     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (11092): #23     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (11092): #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (11092):
```

**Comment by pedrostick3** [comment]
@TatankaConCube another thing, i think it is not `tonal`, it's `total`:
![image](https://user-images.githubusercontent.com/26680498/211809020-9eea6580-b572-4021-8936-47f90af28872.png)

**Comment by TatankaConCube** [comment]
I can't see any stanza packages. Please provide here request and response for sending the reaction. The received XMPP stanza should look similar to next:
```xml
<message type="..." xmlns="jabber:client" to="..." id="..." from="...">
  <extraParams xmlns="jabber:client">
    <dialog_id>6304b6a59cf9db00200c1cf7</dialog_id>
  </extraParams>
  <reactions user_id="89209" message_id="5c094687e588ce59fff87425">
    <reaction add="true" type="👍"/>
    <reaction remove="true" type="👎"/>
  </reactions>
</message>
```
and you will get an error if it looks a different way.

> i use to add the reaction is Android (Flutter) using your Server API requests

why don't you use integrated API? please see our [documentation](https://developers.connectycube.com/flutter/messaging?id=message-reactions) on how to use it in a simple way

**Comment by TatankaConCube** [comment]
use `CubeSettings.instance.isDebugEnabled = true` to enable the XMPP logging

**Comment by pedrostick3** [comment]
I was using the `2.2.3` version and in that moment there wasn't any methods about MessageReactions (neighter any documentation for Flutter) so i moved on with raw server api requests, handling JSONs, and then i upgrated to `2.3.0` version and it continued to work that way.
Right now, in this new `2.4.0` version it has a better and completed implementation for Flutter (with new Objects and methods) but my `2.3.0` version method handling JSONs does not work anymore.
I need to test it and change some implementations and when it's over I'll say something.

**Comment by pedrostick3** [comment]
I have changed/updated everything (flutter package request methods and flutter objects) and this keeps showing the same bug.

full logs with stanza:
```
I/flutter (14400): CB-SDK: : =========================================================
I/flutter (14400): === REQUEST ==== cd0dcae5-c683-4b31-811c-aa79126182fd ===
I/flutter (14400): REQUEST
I/flutter (14400):   PUT https://api.connectycube.com/chat/Message/63bdaf13e107a5519a8c6183/reactions
I/flutter (14400): HEADERS
I/flutter (14400):   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 2.4.0, CB-Token: 01AA27F7B80BF827B8048E033ABBB953BF84}
I/flutter (14400): BODY
I/flutter (14400):   {"add":"bad_truth"}
I/flutter (14400):
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='6'/>
I/flutter (14400): CB-SDK: : *********************************************************
I/flutter (14400): *** RESPONSE *** 200 *** cd0dcae5-c683-4b31-811c-aa79126182fd ***
I/flutter (14400): HEADERS
I/flutter (14400):   {cb-token-expirationdate: 2023-01-11 15:30:52 UTC, connection: keep-alive, date: Wed, 11 Jan 2023 13:30:52 GMT, content-length: 0, strict-transport-security: max-age=15768000; includeSubDomains, access-control-expose-headers: CB-Token-ExpirationDate, server: nginx/1.23.1}
I/flutter (14400): BODY
I/flutter (14400):
I/flutter (14400):
[log] ---Xmpp Receiving:---
I/flutter (14400): CB-SDK: : Receive GROUP chat message null
E/flutter (14400): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (14400): #0      getUserIdFromGroupChatJid
E/flutter (14400): #1      new CubeMessage.fromStanza
E/flutter (14400): #2      ChatMessagesManager.acceptMessage
E/flutter (14400): #3      new GlobalMessagesManager._private.<anonymous closure>
E/flutter (14400): #4      _WhereStream._handleData (dart:async/stream_pipe.dart:189:24)
E/flutter (14400): #5      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (14400): #6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (14400): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14400): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14400): #9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (14400): #10     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (14400): #11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (14400): #12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (14400): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14400): #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14400): #15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (14400): #16     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter (14400): #17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (14400): #18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (14400): #19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14400): #20     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (14400): #21     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (14400): #22     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (14400): #23     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (14400): #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (14400):
[log] <message xmlns="jabber:client" to="6782210-6705@chat.connectycube.com" type="groupchat" from="6782210-6705@chat.connectycube.com"><sent xmlns="urn:xmpp:carbons:2"><forwarded xmlns="urn:xmpp:forward:0"><message id="63beba0c22b558002f93f75a" xmlns="jabber:client" to="6705_638720bc0a7533002f09cb10@muc.chat.connectycube.com" type="groupchat" from="6782210-6705@chat.connectycube.com/restapi"><extraParams xmlns="jabber:client"><dialog_id>638720bc0a7533002f09cb10</dialog_id></extraParams><reactions message_id="63bdaf13e107a5519a8c6183" user_id="6782210"><reaction type="bad_truth" add="true"/></reactions></message></forwarded></sent></message>
[log] D/[StanzaParser]: No id found for stanza
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' /><message id="63beba0c22b558002f93f75a" xmlns="jabber:client" type="groupchat" to="6782210-6705@chat.connectycube.com" from="6705_638720bc0a7533002f09cb10@muc.chat.connectycube.com/6782210"><extraParams xmlns="jabber:client"><dialog_id>638720bc0a7533002f09cb10</dialog_id></extraParams><reactions message_id="63bdaf13e107a5519a8c6183" user_id="6782210"><reaction type="bad_truth" add="true"/></reactions><delay xmlns="urn:xmpp:delay" stamp="2023-01-11T13:30:52Z"/></message><r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="8"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="8"/>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='6'/>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='6'/>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='6'/>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='6'/>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='6'/>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='6'/>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='6'/>
```

**Comment by TatankaConCube** [comment]
thanks for your latest log I reproduced it for the group chat, I'm searching for a solution and will publish a fix soon.

**Comment by TatankaConCube** [comment]
looks like it is a server-side issue, we discussed with the server-side team and I notified them about it, will wait for the solution from them

**Comment by TatankaConCube** [comment]
@pedrostick3 server-side team reported that they deployed the fix on the shared server, could you check it on your side?

**Comment by pedrostick3** [comment]
@TatankaConCube it works perfectly now! Nice job! Thanks! :)
